import type { Metadata } from "next";
import { Inter, Nanum_Gothic } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import PopupWrapper from "@/components/PopupWrapper";
import { Suspense } from "react";
import Loading from "@/app/(hexcode)/loading";
import StoreProvider from "@/components/StoreProvider";

const inter = Inter({ subsets: ["latin"] });
const nanum = Nanum_Gothic({ subsets: ["latin"], weight: ["700", "400"] });

export const metadata: Metadata = {
  title: "Daily color",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={nanum.className} suppressHydrationWarning>
        <Providers>
          <StoreProvider>
            <PopupWrapper />
            {children}
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
